### ISSUE TITLE
Where is the powerpc_syscall.H file?

### ISSUE THREAD

**Issue by lianaduenha** [ArchC/powerpc#4]
For some reason, there is no powerpc_syscall.H file inside the repository. 
I've prepared a syscall file based on the mips model. Please validate the code before using it.

/******************************************************
- ArchC Architecture Dependent Syscall header file.  *
- This file is automatically generated by ArchC      *
- WITHOUT WARRANTY OF ANY KIND, either express       *
- or implied.                                        *
- For more information on ArchC, please visit:       *
- http://www.archc.org                               *
-                                                    *
- The ArchC Team                                     *
- Computer Systems Laboratory (LSC)                  *
- IC-UNICAMP                                         *
- http://www.lsc.ic.unicamp.br                       *
  ******************************************************/
# ifndef POWERPC_SYSCALL_H
# define POWERPC_SYSCALL_H
# include "powerpc_arch.H"
# include "powerpc_arch_ref.H"
# include "powerpc_parms.H"
# include "ac_syscall.H"

//powerpc system calls
class powerpc_syscall : public ac_syscall<powerpc_parms::ac_word, powerpc_parms::ac_Hword>, public powerpc_arch_ref
{
public:
  powerpc_syscall(powerpc_arch& ref) : ac_syscall<powerpc_parms::ac_word, powerpc_parms::ac_Hword>(ref, powerpc_parms::AC_RAMSIZE), powerpc_arch_ref(ref) {};
  virtual ~powerpc_syscall() {};

  void get_buffer(int argn, unsigned char\* buf, unsigned int size);
  void set_buffer(int argn, unsigned char\* buf, unsigned int size);
  void set_buffer_noinvert(int argn, unsigned char\* buf, unsigned int size);
  int  get_int(int argn);
  void set_int(int argn, int val);
  void return_from_syscall();
  void set_prog_args(int argc, char **argv);
};
# endif

**Comment by maxiwell** [comment]
The `acsim` generates a template called `model_syscall.H.tmpl` that will be converted to `model_syscall.H`. If the model has the `model_syscall.H` inside, the template will be ignored. As the other models have this file, you may submit a Pull Request to add this file in the PowerPC model.

**Comment by maxiwell** [comment]
PR #5
